version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 weather_app.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

